language: python
python:
  - '3.6'

os:
  - 'linux'

dist: bionic
cache: pip
install:
  - pip install -r ./requirements.txt -q
script:
  - cd torchfurnace/tests
  - python test_furnace.py
  - python test_img2lmdb.py
  - python test_tracer.py
  - echo 'log of test_tracer.py '
  - cat mine_network/logs/expn/log
branches:
  only:
    - master

deploy:
  provider: pypi
  user: "__token__"
  password: $pypi_token
  on:
    tags: true